const Anthropic = require("@anthropic-ai/sdk");

const client = new Anthropic();

const BETAS = [
  "code-execution-2025-08-25",
  "skills-2025-10-02", 
  "files-api-2025-04-14",
];

const EXPORT_FORMAT = "docx";
const SKILL_ID = "pdf";

const LAYOUT_RULES = `
## LAYOUT RULES (highest priority)
- US Letter page, 1-inch margins all sides.
- All tables must use the full page width (~6.5 inches).
- Equal column widths unless a column needs more space.
- Center all tables horizontally.
- Full-width content. No narrow left-only blocks.
- Page breaks between major sections.
- Body text: 11pt, headings 14-22pt bold.
- No overlapping elements, no floating shapes.
- If design conflicts with layout, layout wins.
`;

function buildPromptBasedSystemPrompt() {
  return `You are an elite report designer for ForceEquals.

## DESIGN
Pick any unique professional design style and commit fully.
Brand colors: Navy #1e2761, Blue #1d4ed8, Light blue #eff6ff, Gray #f8f8f6.

## DOCUMENT STRUCTURE
Include: cover page with 3-5 KPI stats, executive summary (2-3 paragraphs),
detailed profiles/sections with stat cards and analysis, comparison table,
4-6 numbered trends with analysis paragraphs, methodology footer.

## CRITICAL TECHNICAL RULES

Your Python script MUST follow this exact pattern:

import subprocess
subprocess.run(["pip", "install", "python-docx"], capture_output=True)

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

doc = Document()
# ... build the full document ...

output_path = "/mnt/user-data/outputs/report.docx"
doc.save(output_path)

# CRITICAL — print base64 so the file can be retrieved
import base64, os
with open(output_path, "rb") as f:
    encoded = base64.b64encode(f.read()).decode("utf-8")
print("FILE_BASE64_START")
print(encoded)
print("FILE_BASE64_END")
print(f"FILENAME:report.docx")

The base64 output block is MANDATORY. Without it the file cannot 
be downloaded. Always include the FILE_BASE64_START/END markers.

Do NOT use docx-js or JavaScript.
Do NOT use reportlab — this is a DOCX, not a PDF.
Target 6-12 pages. Minimum 4 pages.

## BRANDING
Header: "FORCEEQUALS · AI INTELLIGENCE REPORT"
Footer: "Generated by ForceEquals · Powered by Claude AI"

${LAYOUT_RULES}`;
}

function buildJsonBasedSystemPrompt(report) {
  return `You are an elite report designer for ForceEquals.
Generate a professional DOCX from the data below.

## CRITICAL TECHNICAL RULES

Your Python script MUST follow this exact pattern:

import subprocess
subprocess.run(["pip", "install", "python-docx"], capture_output=True)

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

doc = Document()
# ... build document from the report data below ...

output_path = "/mnt/user-data/outputs/report.docx"
doc.save(output_path)

# CRITICAL — print base64 so the file can be retrieved
import base64, os
with open(output_path, "rb") as f:
    encoded = base64.b64encode(f.read()).decode("utf-8")
print("FILE_BASE64_START")
print(encoded)
print("FILE_BASE64_END")
print(f"FILENAME:report.docx")

The base64 output block is MANDATORY. Without it the file cannot 
be downloaded. Always include the FILE_BASE64_START/END markers.

Do NOT use docx-js or JavaScript.
Do NOT use reportlab.

## DESIGN
Pick a unique professional style. Brand colors: Navy #1e2761, 
Blue #1d4ed8, Light blue #eff6ff, Gray #f8f8f6.
Use tables with cell shading for visual elements.
Cover page with KPIs, executive summary, detailed sections,
comparison table, trends, methodology footer.

${LAYOUT_RULES}

## REPORT DATA
${JSON.stringify(report, null, 2)}`;
}

// Extract base64 file content from bash stdout
function extractBase64FromResponse(response) {
  for (var i = 0; i < response.content.length; i++) {
    var block = response.content[i];
    
    if (block.type === "bash_code_execution_tool_result") {
      var stdout = "";
      
      // Extract stdout from the block
      if (block.content && block.content.stdout) {
        stdout = block.content.stdout;
      }
      if (block.content && block.content.type === "bash_code_execution_result") {
        stdout = block.content.stdout || "";
      }
      
      // Look for our base64 markers
      var startMarker = "FILE_BASE64_START";
      var endMarker = "FILE_BASE64_END";
      var startIdx = stdout.indexOf(startMarker);
      var endIdx = stdout.indexOf(endMarker);
      
      if (startIdx !== -1 && endIdx !== -1) {
        var base64Content = stdout
          .substring(startIdx + startMarker.length, endIdx)
          .trim();
        
        // Extract filename
        var filenameMatch = stdout.match(/FILENAME:(.+)/);
        var filename = filenameMatch ? filenameMatch[1].trim() : "report.docx";
        
        console.log("[export] Found base64 content, length:", base64Content.length);
        console.log("[export] Filename:", filename);
        
        return {
          buffer: Buffer.from(base64Content, "base64"),
          filename: filename,
        };
      }
    }
  }
  return null;
}

// Fallback: extract file IDs from Files API (works for PDF)
function extractFileIds(response) {
  var fileIds = [];
  
  function searchForFileIds(obj) {
    if (!obj || typeof obj !== "object") return;
    if (obj.file_id && typeof obj.file_id === "string") {
      fileIds.push(obj.file_id);
    }
    if (Array.isArray(obj)) {
      for (var i = 0; i < obj.length; i++) searchForFileIds(obj[i]);
      return;
    }
    var keys = Object.keys(obj);
    for (var i = 0; i < keys.length; i++) {
      var val = obj[keys[i]];
      if (val && typeof val === "object") searchForFileIds(val);
    }
  }
  
  if (response && response.content && Array.isArray(response.content)) {
    for (var i = 0; i < response.content.length; i++) {
      searchForFileIds(response.content[i]);
    }
  }
  
  return fileIds.filter(function(id, idx, arr) { 
    return arr.indexOf(id) === idx; 
  });
}

async function exportReport(input) {
  var format = EXPORT_FORMAT;
  var isPromptBased = typeof input === "string";
  
  var systemPrompt;
  var userMessage;
  
  if (isPromptBased) {
    systemPrompt = buildPromptBasedSystemPrompt();
    userMessage = input + "\n\nGenerate a DOCX report. "
      + "FIRST pip install python-docx, THEN build the document, "
      + "THEN save and print the base64 with FILE_BASE64_START/END markers.";
  } else {
    systemPrompt = buildJsonBasedSystemPrompt(input);
    userMessage = "Generate a DOCX report from the data above. "
      + "FIRST pip install python-docx, THEN build the document, "
      + "THEN save and print the base64 with FILE_BASE64_START/END markers.";
  }
  
  console.log("[export] Calling Claude API with streaming...");
  var stream = await client.beta.messages.stream({
    model: "claude-sonnet-4-6",
    max_tokens: 16000,
    betas: BETAS,
    system: systemPrompt,
    container: {
      skills: [
        { type: "anthropic", skill_id: SKILL_ID, version: "latest" },
      ],
    },
    messages: [
      { role: "user", content: userMessage },
    ],
    tools: [
      { type: "code_execution_20250825", name: "code_execution" },
    ],
  });
  var response = await stream.finalMessage();

  console.log("[export] Stop reason:", response.stop_reason);
  console.log("[export] Block types:", response.content.map(function(b) { return b.type; }));
  
  // Log all blocks for debugging
  response.content.forEach(function(block, i) {
    if (block.type === "bash_code_execution_tool_result") {
      var stdout = "";
      if (block.content && block.content.stdout) stdout = block.content.stdout;
      if (block.content && block.content.type === "bash_code_execution_result") stdout = block.content.stdout || "";
      console.log("[export] Bash block " + i + " stdout:", stdout.substring(0, 500));
      if (block.content && block.content.stderr) {
        console.log("[export] Bash block " + i + " stderr:", block.content.stderr.substring(0, 500));
      }
      if (block.content && block.content.type === "bash_code_execution_result" && block.content.stderr) {
        console.log("[export] Bash block " + i + " stderr:", block.content.stderr.substring(0, 500));
      }
    }
    if (block.type === "text") {
      console.log("[export] Text block " + i + ":", block.text.substring(0, 500));
    }
  });

  // Continuation loop
  var maxTurns = 5;
  var currentResponse = response;

  while (maxTurns > 0) {
    var lastBlock = currentResponse.content[currentResponse.content.length - 1];
    var needsContinuation = 
      currentResponse.stop_reason === "tool_use" ||
      lastBlock.type === "server_tool_use" ||
      lastBlock.type === "tool_use";
    
    if (!needsContinuation) break;
    
    console.log("[export] Continuing...");
    
    var contStream = await client.beta.messages.stream({
      model: "claude-sonnet-4-6",
      max_tokens: 16000,
      betas: BETAS,
      system: systemPrompt,
      container: {
        skills: [
          { type: "anthropic", skill_id: SKILL_ID, version: "latest" },
        ],
      },
      messages: [
        { role: "user", content: userMessage },
        { role: "assistant", content: currentResponse.content },
        { role: "user", content: "Continue. Save the DOCX and print base64 "
          + "with FILE_BASE64_START/END markers." },
      ],
      tools: [
        { type: "code_execution_20250825", name: "code_execution" },
      ],
    });
    currentResponse = await contStream.finalMessage();
    maxTurns--;
  }

  // METHOD 1: Try to extract base64 from stdout (reliable for DOCX)
  var base64Result = extractBase64FromResponse(currentResponse);
  if (!base64Result && currentResponse !== response) {
    base64Result = extractBase64FromResponse(response);
  }
  
  if (base64Result) {
    console.log("[export] Success via base64:", base64Result.filename, base64Result.buffer.length, "bytes");
    return base64Result;
  }

  // METHOD 2: Fallback — try Files API (works for PDF)
  var allFileIds = extractFileIds(currentResponse);
  if (allFileIds.length === 0 && currentResponse !== response) {
    allFileIds = extractFileIds(response);
  }

  if (allFileIds.length > 0) {
    console.log("[export] Found file IDs:", allFileIds);
    var fileId = allFileIds[0];
    var metadata = await client.beta.files.retrieveMetadata(fileId);
    var fileContent = await client.beta.files.download(fileId);

    var chunks = [];
    var reader = fileContent.body.getReader();
    while (true) {
      var result = await reader.read();
      if (result.done) break;
      if (result.value) chunks.push(result.value);
    }
    var buffer = Buffer.concat(chunks);
    await client.beta.files.delete(fileId).catch(function() {});

    console.log("[export] Success via Files API:", metadata.filename, buffer.length, "bytes");
    return { buffer: buffer, filename: metadata.filename || "report.docx" };
  }

  console.error("[export] Both methods failed. No base64 and no file_id found.");
  throw new Error("Claude generated the file but it could not be retrieved. Check logs.");
}

module.exports = { exportReport };