const Anthropic = require("@anthropic-ai/sdk");

const client = new Anthropic();
// Reads ANTHROPIC_API_KEY from .env automatically

const BETAS = [
  "code-execution-2025-08-25",
  "skills-2025-10-02", 
  "files-api-2025-04-14",
];

const EXPORT_FORMAT = "docx";
const DOCX_SKILL_ID = "docx";

function buildPromptBasedSystemPrompt() {
  return `You are an elite report designer who creates documents 
that look like they were produced by a professional consulting firm 
like McKinsey, BCG, or Goldman Sachs.

CRITICAL: You are NOT constrained to any JSON schema. You decide 
the entire document structure based on the topic. Research the 
topic thoroughly using your knowledge, then design a comprehensive, 
multi-page document with rich content.

## DESIGN VARIETY
Pick ONE design direction randomly and commit fully:

RECIPE A — "Corporate Intelligence" (navy + blue)
  - Navy (#1e2761) header bar, white title text
  - KPI cards with blue (#1d4ed8) top accents on gray (#f8f8f6) bg
  - Clean tables with dark header rows
  - Blue left-border insight blocks on light blue (#eff6ff) bg
  - Professional, structured, boardroom feel

RECIPE B — "Dark Dossier" (near-black + white)
  - Near-black (#0e0e10) cover page
  - White text on dark backgrounds for headers
  - Monochrome data tables, no color accents
  - Dense, compact layout
  - Intelligence briefing feel

RECIPE C — "Editorial Premium" (warm + serif)
  - Off-white (#faf8f5) background
  - Serif fonts (Times-Bold headings, Times-Roman body)
  - Gold (#d4af37) accent lines
  - Minimal table borders, generous whitespace
  - Financial magazine feel

RECIPE D — "Vibrant Dashboard" (colorful + modern)
  - White background with colored section bands
  - Multiple accent colors (blue, green, coral, orange)
  - Colored pill badges for status indicators
  - Bold visual hierarchy
  - Modern SaaS report feel

## DOCUMENT STRUCTURE GUIDELINES

For ANY topic, your document should include:

1. COVER PAGE (required)
   - Full visual cover — not just a title
   - 3-5 key statistics displayed prominently
   - Report title, subtitle, date

2. EXECUTIVE SUMMARY (required)
   - 2-3 paragraph overview
   - Key findings highlighted

3. DETAILED SECTIONS (topic-dependent)
   - For company/industry reports: company profiles with stat cards
   - For country/city reports: location profiles with key metrics
   - For financial reports: data tables with trend indicators
   - For comparison reports: side-by-side analysis tables
   - For investment reports: funding tables with deal details
   
   Each profile/section should include:
   - A header with the entity name and category
   - 3-5 key statistics in visual card/box format
   - 2-3 paragraphs of analysis
   - Key strengths or highlights as bullet points
   - Major players/institutions if relevant

4. COMPARISON TABLE (when applicable)
   - Rating systems (stars, bars, or scores)
   - Multiple dimensions compared
   - Visual formatting (colored cells, icons)

5. KEY TRENDS / INSIGHTS SECTION
   - 4-6 numbered trend items
   - Each with a bold heading and analysis paragraph

6. METHODOLOGY / SOURCES FOOTER
   - Data sources cited
   - Disclaimer if applicable

## TECHNICAL RULES

- Use python-docx for DOCX generation
- Use Word styles, tables, shaded cells, and paragraph formatting for 
  visual hierarchy (cover title, KPI tables, comparison grids, insight blocks)
- Include page breaks between major sections where appropriate
- For metrics: use bordered/shaded table cells or a 2x2 KPI grid
- For comparisons: formatted tables with header row styling
- Save to /mnt/user-data/outputs/ — CRITICAL

- Target 6-12 pages for comprehensive topics. Never produce less 
  than 4 pages. Depth and detail are more important than brevity.

## FORCEEQUALS BRANDING

- Brand colors: Navy #1e2761, Blue #1d4ed8, Light blue #eff6ff, 
  Card gray #f8f8f6, Dark text #111111, Muted #888888
- Footer on every page: 
  "Generated by ForceEquals · Powered by Claude AI"
- Header: "FORCEEQUALS · AI INTELLIGENCE REPORT"
- Page numbers: "Page X of Y"`;
}

function buildJsonBasedSystemPrompt(report) {
  const recipes = [
    `### RECIPE A — "Dark Intelligence" (like a classified briefing)
  - Background: near-black (#0e0e10) for header/cover area
  - Full-width dark header bar covering top 25% of first page
  - Title: white text, large bold sans-serif on dark background
  - Subtitle: gray (#9ca3af) smaller text below title
  - KPI strip: 4 large numbers in a horizontal row ON the dark header
    Each number: white, 36pt bold
    Each label: gray, 9pt below the number
  - Body: white page background
  - Section headings: dark text with thin gray underline
  - Tables: dark header row (#1a1a1a bg, white text), alternating 
    white/#f5f5f5 body rows, thin gray borders
  - No color accents — monochrome palette only
  - Compact spacing, data-dense
  - Footer: thin gray line, disclaimer text in 7pt gray
  - Overall feel: military intelligence briefing`,
    
    `### RECIPE B — "Corporate Executive" (like a McKinsey deck)
  - Background: white page, navy (#1e2761) header bar at top
  - Title: navy or white text (white if on navy bar)
  - Badge: "LIVE REPORT · 2026" in small blue pill shape
  - KPI strip: 4 metric CARDS with colored top borders
    Each card: light gray bg (#f8f8f6), blue (#1d4ed8) top accent bar
    Value large and bold, label small and muted, trend with arrow
  - Sections separated by thin blue divider lines
  - Tables: blue header row, clean grid, professional spacing
  - Insight blocks: blue left border bar + light blue (#eff6ff) background
  - Color accents: navy, blue, light blue
  - Generous whitespace, editorial spacing
  - Footer: branded with page numbers
  - Overall feel: boardroom presentation`,

    `### RECIPE C — "Editorial Magazine" (like The Economist)
  - Background: warm off-white (#faf8f5)
  - Title: large serif font (Times-Bold), dark brown/charcoal text
  - Subtitle: italic serif, muted color
  - NO header bar — title floats on the page
  - KPI strip: numbers inline with body text, bold and large
    with thin gold (#d4af37) underline beneath each number
  - Body text: serif font (Times-Roman), 10pt, well-spaced
  - Section headings: small caps, letter-spaced, with gold rule below
  - Tables: minimal — thin top/bottom borders only, no vertical lines
    Header row: bold text, no background color
  - Insight blocks: indented with thin gold left rule
  - Pull quotes: large italic serif text with quotation marks
  - Wide margins (1.2 inches), single column
  - Footer: page number centered, small serif
  - Overall feel: premium financial magazine`,

    `### RECIPE D — "Vibrant Dashboard" (like a modern SaaS report)
  - Background: white with colored section bands
  - Title: bold sans-serif, dark text
  - Colored gradient bar at very top (4px, blue to purple)
  - KPI strip: colored PILL shapes, each a different color
    Revenue: green pill, Users: blue pill, Growth: orange pill
  - Charts: use filled shapes and colored bars prominently
  - Tables: rounded corners (simulated), colored tag cells
    Status columns use colored dots or filled rectangles
  - Insight blocks: each has different colored left bar 
    (blue, green, orange rotating)
  - Use icons/symbols: ▲ ▼ ● ■ for visual variety
  - Modern spacing, clean grid alignment
  - Footer: colorful thin line, brand text
  - Overall feel: Notion or Linear product report`,

    `### RECIPE E — "Dossier / Classified" (like a government file)
  - Background: slightly yellowed/aged (#f5f2eb)
  - "CLASSIFIED" or "CONFIDENTIAL" stamp at top (rotated slightly)
  - Title: monospace font (Courier-Bold), all caps
  - Subtitle: Courier, smaller, with file reference number
  - Date stamp: "COMPILED: MAY 2026 | REF: FE-2026-0531"
  - KPI strip: boxed with double borders, typewriter style
  - Body text: Courier 9pt, dense paragraphs
  - Section dividers: double horizontal rules
  - Tables: heavy borders, Courier font, all caps headers
  - Insight blocks: boxed with "ANALYSIS:" prefix in bold
  - Redaction-style black bars for visual decoration (not hiding text)
  - Footer: "Page X of Y — DISTRIBUTION: INTERNAL ONLY"
  - Overall feel: declassified intelligence document`,

    `### RECIPE F — "Infographic Poster" (like a visual data story)
  - First page: full infographic-style cover
  - Large title text overlapping colored shapes
  - KPI strip: huge numbers (48pt+) with small labels
    Arranged in 2x2 grid, each in its own colored box
  - Use color blocks aggressively — full-width colored bands 
    between sections
  - Bar charts drawn as actual colored rectangles (not tables)
  - Progress bars for metrics (filled/unfilled rectangles)
  - Circular indicators for percentages (simulated with shapes)
  - Icon-like symbols before each section heading
  - Minimal body text — let the visuals tell the story
  - Bold color palette: navy, coral (#f96167), gold (#f9e795)
  - Footer: thin colored band
  - Overall feel: conference poster or annual report infographic`
  ];

  const randomRecipe = recipes[Math.floor(Math.random() * recipes.length)];

  return `You are an elite report designer. You generate 
DOCX documents that look like they were designed 
by a professional graphic design agency — not a template engine.

## THE MOST IMPORTANT RULE: DESIGN VARIETY

You MUST strictly follow the design recipe provided below and commit fully to it.

${randomRecipe}

---
## RULES FOR ALL RECIPES

1. Use python-docx with tables, headings, and cell shading for visual 
   elements (metric cards, data tables, insight blocks). Never use plain 
   text-only layouts.

2. The cover/first page must have a distinct visual treatment — 
   it should look like a cover, not like page 1 of body text.

3. The KPI strip must be prominent and visual — large numbers 
   with labels in a formatted table or grid, not buried in body text.

4. Represent bar chart data as a formatted table with values and 
   optional shaded cells to show relative magnitude.

5. Every section must be visually separated (page breaks, headings, 
   horizontal rules, or table spacing).

6. Save output to /mnt/user-data/outputs/ — this is CRITICAL.

7. If any section data is missing or empty, skip it gracefully.

8. Output must be a valid .docx file using python-docx only.

---
## REPORT DATA

${JSON.stringify(report, null, 2)}

Generate the DOCX file now. Commit fully to your 
chosen design recipe. Make it look like a professional design agency 
produced it, not a code generator.`;
}

async function exportReport(input) {
  var format = EXPORT_FORMAT;
  var isPromptBased = typeof input === "string";
  
  var systemPrompt;
  var userMessage;
  
  if (isPromptBased) {
    systemPrompt = buildPromptBasedSystemPrompt();
    userMessage = input + "\n\nGenerate a comprehensive, multi-page DOCX "
      + "report on this topic. Include detailed profiles, data tables, "
      + "comparison metrics, trends analysis, and visual elements. "
      + "Make it at least 6 pages. Use real data from your knowledge.";
  } else {
    systemPrompt = buildJsonBasedSystemPrompt(input);
    userMessage = "Generate a DOCX report from the data provided in the system prompt.";
  }
  
  console.log("[export] Calling Claude API with streaming...");
  var stream = await client.beta.messages.stream({
    model: "claude-sonnet-4-6",
    max_tokens: 32000,
    betas: BETAS,
    system: systemPrompt,
    container: {
      skills: [
        { type: "anthropic", skill_id: DOCX_SKILL_ID, version: "latest" },
      ],
    },
    messages: [
      { role: "user", content: userMessage },
    ],
    tools: [
      { type: "code_execution_20250825", name: "code_execution" },
    ],
  });
  var response = await stream.finalMessage();

  console.log("[export] Response stop_reason:", response.stop_reason);
  console.log("[export] Block types:", response.content.map(function(b) { return b.type; }));
  console.log("[export] Full response (first 2000 chars):", JSON.stringify(response.content).substring(0, 2000));

  var maxTurns = 5;
  var currentResponse = response;

  while (maxTurns > 0) {
    var lastBlock = currentResponse.content[currentResponse.content.length - 1];
    var needsContinuation = 
      currentResponse.stop_reason === "tool_use" ||
      lastBlock.type === "server_tool_use" ||
      lastBlock.type === "tool_use";
    
    if (!needsContinuation) break;
    
    console.log("[export] Claude needs another turn, continuing...");
    
    var contStream = await client.beta.messages.stream({
      model: "claude-sonnet-4-6",
      max_tokens: 32000,
      betas: BETAS,
      system: systemPrompt,
      container: {
        skills: [
          { type: "anthropic", skill_id: DOCX_SKILL_ID, version: "latest" },
        ],
      },
      messages: [
        { role: "user", content: userMessage },
        { role: "assistant", content: currentResponse.content },
        { role: "user", content: "Continue. Complete the file generation and save the output." },
      ],
      tools: [
        { type: "code_execution_20250825", name: "code_execution" },
      ],
    });
    currentResponse = await contStream.finalMessage();
    
    console.log("[export] Continuation response. Stop reason:", currentResponse.stop_reason);
    maxTurns--;
  }

  var allFileIds = extractFileIds(currentResponse);

  if (allFileIds.length === 0 && currentResponse !== response) {
    allFileIds = extractFileIds(response);
  }

  if (allFileIds.length === 0) {
    console.error("No files in response.");
    throw new Error("Claude did not generate any files");
  }

  var fileId = allFileIds[0];
  var metadata = await client.beta.files.retrieveMetadata(fileId);
  var fileContent = await client.beta.files.download(fileId);

  var chunks = [];
  var reader = fileContent.body.getReader();
  while (true) {
    var result = await reader.read();
    if (result.done) break;
    if (result.value) chunks.push(result.value);
  }
  var buffer = Buffer.concat(chunks);

  await client.beta.files.delete(fileId).catch(function() {});

  return {
    buffer: buffer,
    filename: metadata.filename || "report.docx",
  };
}

function extractFileIds(response) {
  var fileIds = [];
  
  function searchForFileIds(obj) {
    if (!obj || typeof obj !== "object") return;
    
    if (obj.file_id && typeof obj.file_id === "string") {
      fileIds.push(obj.file_id);
    }
    
    if (obj.type === "file" && obj.file_id) {
      fileIds.push(obj.file_id);
    }
    
    if (Array.isArray(obj)) {
      for (var i = 0; i < obj.length; i++) {
        searchForFileIds(obj[i]);
      }
      return;
    }
    
    var keys = Object.keys(obj);
    for (var i = 0; i < keys.length; i++) {
      var val = obj[keys[i]];
      if (val && typeof val === "object") {
        searchForFileIds(val);
      }
    }
  }
  
  if (response && response.content && Array.isArray(response.content)) {
    for (var i = 0; i < response.content.length; i++) {
      searchForFileIds(response.content[i]);
    }
  }
  
  var unique = [];
  for (var i = 0; i < fileIds.length; i++) {
    if (unique.indexOf(fileIds[i]) === -1) {
      unique.push(fileIds[i]);
    }
  }
  
  return unique;
}

module.exports = { exportReport };
